### ISSUE TITLE
Issues with polymorphic associations

### ISSUE THREAD

**Issue by railsfactory-selva** [yosiat/panko_serializer#56] opened 2019-09-18 11:10 UTC
post.rb & comment.rb
has_many :attachments, dependent: :destroy, :as => :attachable

attachment.rb
belongs_to :attachable, polymorphic: true

Attachable is common to both post and comment. Attachment should be referring multiple serializers like PostSerializer and CommentSerializer. Is it possible?

It would be nice, if we Panko detects serializers automatically according to associations.

**Comment by yosiat** [comment] 2020-01-11 11:49
@railsfactory-selva sorry for the late response!

Can you please create a reproduction with ActiveRecord bug template - https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb  ?

**Comment by yosiat** [comment] 2020-03-09 22:03
@railsfactory-selva closing this issue, since we have another issue which is raising the same questions and issue and it's more active - https://github.com/yosiat/panko_serializer/issues/65.

If you have any feedback, please post it their.

**Closed by yosiat** 2020-03-09 22:03 UTC
Labels: waiting for response
